on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Validate Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v12
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3.13.0
      - name: Build default package
        run: nix build
      - name: Run
        run: result/bin/voxinput ver
