name: Validate Tag
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Validate Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v12
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3.13.0
      - name: Build default package
        run: nix build
      - name: Run
        run: result/bin/voxinput ver
      - name: Check tag against voxinput ver
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=$(./result/bin/voxinput ver | tr -d '[:space:]')
          if [ "$TAG_NAME" != "$VERSION" ]; then
            echo "Error: Tag '$TAG_NAME' does not match voxinput ver output '$VERSION'"
            exit 1
          fi
